export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const  OTP_REQUEST = 'OTP_REQUEST';
export const  OTP_SUCCESS = 'OTP_SUCCESS';
export const  OTP_FAIL = 'OTP_FAIL';

export const EMAIL_OTP_REQUEST= 'EMAIL_OTP_REQUEST';
export const  EMAIL_OTP_SUCCESS = 'EMAIL_OTP_SUCCESS';
export const  EMAIL_OTP_FAIL = 'EMAIL_OTP_FAIL';

export const  CONFIRM_OTP_REQUEST = 'CONFIRM_OTP_REQUEST';
export const  CONFIRM_OTP_SUCCESS = 'CONFIRM_OTP_SUCCESS';
export const  CONFIRM_OTP_FAIL = 'CONFIRM_OTP_FAIL';
